#ifndef MATROSKA_HPP
#define MATROSKA_HPP


enum matroska/*{{{*/
	{	NEXT = 0,
		BEGIN,
		TOGGLE_WORK_MODE,
		SELECT,
		INTRO,
		CHANGE_WINDOW,
		MOVE_INDEX,
		DRAG_UP,
		DRAG_DOWN,
		TO_PREV_SCENE, TO_NEXT_SCENE,
		DIAL_FAVOURITE,
		CHANGE_HOTKEYS_BEHAVIOR,
		CHANGE_SCENE,
		ADD_TO_PLAYLIST,
		DEL_FROM_PLAYLIST,
		COPY_ORCHESTRATION,
		PASTE_ORCHESTRATION,
		RESET_QUERY,
		DECREASE_QUERY,
		INCREASE_QUERY,
		SAVE_PLAYLIST,
		LOAD_PLAYLIST,
		CLEAR_PLAYLIST,
		FAVOURITE,
		RELOAD_CONNECTIONS,
		ADD_VALUE,
		EDIT_VALUE,
		EDIT_ORCHESTRATION,
		DELETE_VALUE,
		EXPORTATE,
		SELECT_PART,
		TOGGLE_MIDI_STATE,
		EXIT,
		EXPORTATE_AND_QUIT };/*}}}*/

enum matroska get_command(	const int digit,
							const short mode, short windowMode,
							char cadena[], short int ci,
							int dIndex ) noexcept;

#endif
